easy_admin:
    design:
        menu:
            - { route: 'admin', label: 'Dashboard' }
            - { entity: 'App\Entity\ShipmentEntity', label: 'ShipmentEntity' }
    entities:
        ShipmentEntity:
            class: App\Entity\ShipmentEntity
            form:
                fields:
                    - { property: 'tracknumber', type: 'text' }
                    
    controllers:
        ShipmentEntity: App\Controller\Admin\ShipmentEntityCrudController