version: '3.8'  # Docker Compose sürümünü uygun bir şekilde belirtin

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scpsw
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./app:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - symfony

  php:
    image: php:8.0-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony


volumes:
  database_data:

networks:
  symfony:
