controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
logout:
    path: /logout
login:
    path: /login

index:
    path: /
    controller: App\Controller\ShipController::index
shipment:
    path: /shipment
    controller: App\Controller\ShipmentController::shipment
shipments:
    path: /shipments
    controller: App\Controller\ShipmentController::shipments