controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
logout:
    path: /logout
login:
    path: /login

index:
    path: /
    controller: App\Controller\ShipController::index